backend:
  name: git-gateway
  branch: master

media_folder: content/images
collections:
- name: articles
  label: Articles
  label_singular: Article
  folder: articles
  create: true
  editor:
    preview: false
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  path: '{{slug}}/index'
  media_folder: ''
  fields:
    - label: Title
      name: title
      widget: string
      pattern: ['.{2,30}', "Must be between 3 and 20 characters"]
    - label: Featured Image
      name: featured_image
      widget: image
      default: /images/defaultArticle.png
    - label: Date
      name: date
      widget: datetime
    - label: Language
      name: language
      widget: select
      options:
        - { label: "English", value: "en" }
        - { label: "Español", value: "es" }
      default: "en"
    - label: Body
      name: body
      widget: markdown
